[versions]
kotlin = "2.4.10"
clikt = "5.1.0"
spotless = "8.9.0"
kaitai = "0.11"
coroutines = "1.11.0"
kstatemachine = "0.38.1"
ktor = "3.5.2"
slf4j = "2.0.18"
tink = "1.23.0"
kyber = "2.0.1"
jbcrypt = "1.0.2"
junit = "6.1.3"
equalsverifier = "4.5"
mockk = "1.14.11"
logback = "1.6.2"
testcontainers = "2.0.5"
metalava = "0.5.0"
dokka = "2.2.0"
publish = "0.37.0"
release = "3.1.0"
kover = "0.9.9"
cyclonedx = "3.4.0"
sonarqube = "7.3.1.8318"

[libraries]
kaitai-runtime = { module = "io.kaitai:kaitai-struct-runtime", version.ref = "kaitai" }
kaitai-compiler = { module = "io.kaitai:kaitai-struct-compiler_2.13", version.ref = "kaitai" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kstatemachine = { module = "io.github.nsk90:kstatemachine-jvm", version.ref = "kstatemachine" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
kyber = { module = "asia.hombre:kyber", version.ref = "kyber" }
jbcrypt = { module = "org.connectbot:jbcrypt", version.ref = "jbcrypt" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsverifier" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
metalava = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalava" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
release = { id = "net.researchgate.release", version.ref = "release" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
