# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Submit pull request dependency graph
on:
  workflow_run:
    workflows: ['Dependency Submission']
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  submit-dependency-graph:
    name: Submit pull request dependency graph
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download and submit dependency graph
        uses: gradle/actions/dependency-submission@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1
        with:
          dependency-graph: download-and-submit
